export default [
    {
        id: 12,
        name: '글의 목적',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 13,
        name: '글의 분위기 / 심경',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 14,
        name: '글의 주장',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 15,
        name: '글의 요지',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 16,
        name: '글의 제목',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 17,
        name: '글의 주제',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 18,
        name: '도표 이해',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 19,
        name: '내용 일치 / 불일치',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 20,
        name: '실용문 일치 / 불일치',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 21,
        name: '어법성 판단',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 22,
        name: '단어 쓰임 판단',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 23,
        name: '지칭 추론',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 24,
        name: '빈칸 추론',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 25,
        name: '무관한 문장 고르기',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 26,
        name: '문단 순서 맞추기',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 27,
        name: '주어진 문장 넣기',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 28,
        name: '요약문 완성',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 29,
        name: '장문 독해 I',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 30,
        name: '장문 독해 II',
        eng: '',
        desc: '',
        nums: '',
    },
    {
        id: 11,
        name: '기타',
        eng: 'Others',
        desc: '기타 유형',
        nums: '',
    },
];
